version: '3.7'

services:
  application_name:
    build: ./app_api
    volumes:
        - ./app_api/:/code/src/django_app/
        - static_volume:/code/src/django_app/staticfiles
    expose:
        - 8000
    env_file:
        - local.env  
  nginx:
        build: ./nginx
        ports: 
                - 80:80
        volumes:
                - static_volume:/code/src/django_app/staticfiles
        depends_on:
                - application_name
volumes:
  static_volume:

